#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ -z "$1" ]; then
  echo "Error: You must define a version number to inject into the build"
  exit 1
fi

VERSION=$1
echo "==> Building provider version $VERSION"
GOOS=${GOOS:-linux}
GOARCH=${GOARCH:-amd64}
if [ "$ADM64" = 1 ]; then
  GOOS=${GOOS:-linux}
  GOARCH=${GOARCH:-amd64}
  GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-s -w -X main.version=$VERSION" -o terraform-provider-cloudflare
else
  go build -ldflags="-s -w -X main.version=$VERSION" -o terraform-provider-cloudflare
fi
